### ISSUE TITLE
Failed to activate the rails-navigation package

### ISSUE THREAD

**Issue by linjunpop** [fotanus/rails-navigation#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [rails-navigation](https://github.com/fotanus/rails-navigation) package, v1.0.0
### Stack Trace

Failed to activate the rails-navigation package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/linjunpop/.atom/packages/rails-navigation/lib/rails-navigation.coffee:8:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:738:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:27.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:27.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:27.3.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -0:27.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  8x -0:26 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:22.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:17.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:17.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:16.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 rails:go-to-controller (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "native-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
language-emblem, v0.2.0
language-json5, v1.1.0
linter, v1.11.2
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-write-good, v0.6.1
local-history, v3.2.3
minimap, v4.16.2
minimap-git-diff, v4.1.8
native-ui, v0.9.0
pangu, v0.3.0
pigments, v0.19.0
rails-navigation, v1.0.0
ruby-slim, v0.2.0
show-ideographic-space, v1.0.1
trailing-spaces, v0.3.2
vim-mode, v0.63.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by fotanus** [comment]
Unfortunately I don't have interest in keep the development of this package any longer. You can keep its development if it will be useful for you

**Comment by linjunpop** [comment]
Oh, sorry to hear that.

Maybe @cliffrowley want to take over this project. 

ref: https://github.com/fotanus/rails-navigation/issues/4#issuecomment-109341968

**Comment by fotanus** [comment]
unfortunately he never replied on #5

**Comment by linjunpop** [comment]
Hi @fotanus I found a similar project https://github.com/hmatsuda/rails-transporter, and that one seems works good. Maybe it's time to deprecate this package and suggest others use `rails-transporter`?

**Comment by fotanus** [comment]
There is a link for rails-transporter on the README.md. Not sure how to deprecate?

**Comment by fotanus** [comment]
I managed to unpublish it, so hopefully it will not be listed on atom when searching packages.

**Comment by linjunpop** [comment]
@fotanus Cool. And I gonna close this issue.

**Comment by cliffrowley** [comment]
Hello, apologies for my late response.  Unfortunately it seems I just won't have any time to work on this in the near future, sorry :-)
